apiVersion: v2
name: protonmail-bridge
description: A Helm chart for the ProtonMail Bridge
type: application
version: 0.1.2
# This is the version of the application being deployed.
# It is a good practice to keep this in sync with the image tag.
appVersion: "latest"
maintainers:
  - name: digrouz
    email: digrouz+github@proton.me
