FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG BRIDGE_VERSION=''

### Environment variables
ENV BRIDGE_VERSION="${BRIDGE_VERSION}" \
    CGO_CFLAGS="-D_LARGEFILE64_SOURCE"

### Copy files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      bash \
      ca-certificates \
      curl \
      git \
      go \
      libsecret-dev \
      make \
      pkgconfig \
    && \
    cd /tmp && \
    git clone --depth 1 --branch v${BRIDGE_VERSION} https://github.com/ProtonMail/proton-bridge.git /tmp/proton-bridge && \
    cd /tmp/proton-bridge && \
    make build-nogui && \
    mkdir -p /opt/protonmail/bin/ && \
    cp /tmp/proton-bridge/proton-bridge /opt/protonmail/bin/ && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      gpg-agent \
      libsecret \
      pass \
      socat \
      su-exec \
    && \
    apk del --no-cache build-deps && \
    mkdir /docker-entrypoint.d && \
    rm -rf /root/.cache \
           /root/go \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* 
    
### Volume
#Volume ["/volume1"]

### Expose ports
Expose 25/tcp
Expose 143/tcp
