#!/command/with-contenv sh

echo "Generate gpg key"
su-exec appuser gpg --generate-key --batch /opt/protonmail/etc/gpg-parameters
echo "Init password manager"
su-exec appuser pass init proton-key
  
echo "Init Bridge"
exec su-exec appuser /opt/protonmail/bin/proton-bridge --cli init
