apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "protonmail-bridge.fullname" . }}
  labels:
    {{- include "protonmail-bridge.selectorLabels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "protonmail-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "protonmail-bridge.podLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UID
              value: {{ .Values.env.uid | quote }}
            - name: GID
              value: {{ .Values.env.gid | quote }}
            - name: AUTOUPGRADE
              value: {{ .Values.env.autoupgrade | quote }}
            - name: TZ
              value: {{ .Values.env.timezone | quote }}
          ports:
            - name: imap
              containerPort: {{ .Values.service.ports.imap }}
              protocol: TCP
            - name: smtp
              containerPort: {{ .Values.service.ports.smtp }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: protonmail-bridge-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: protonmail-bridge-data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "protonmail-bridge.fullname" . }}-data
          {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}