---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "protonmail-bridge.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: protonmail-bridge
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.imap }}
    name: imap
    protocol: TCP
  - port: {{ .Values.service.ports.smtp }}
    name: smtp
    protocol: TCP
  selector:
    app.kubernetes.io/component: protonmail-bridge
