apiVersion: v1
kind: Service
metadata:
  name: {{ include "protonmail-bridge.fullname" . }}
  labels:
    {{- include "protonmail-bridge.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $portName, $port := .Values.service.ports }}
    - name: {{ $portName }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "protonmail-bridge.selectorLabels" . | nindent 4 }}