{{- if .Values.gatewayApi.enabled }}
{{- range .Values.gatewayApi.tcpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "protonmail-bridge.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: protonmail-bridge
spec:
  parentRefs:
    {{- range .parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{- end }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "protonmail-bridge.fullname" $ }}-svc
          port: {{ .port }}
{{- end }}
{{- end }}
