# This is a basic workflow to help you get started with Actions

name: update-golang-workflow

# Controls when the action will run. 
on:
  schedule:
  - cron: "30 2 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-golang-job:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: configure git
        run: |
          git config --global user.email "nicolas.digregorio@gmail.com"
          git config --global user.name "Nicolas DI GREGORIO"
      - name: run update-golang.sh
        run: |
          echo "Run update-golang.sh"
          bash .github/scripts/update-golang.sh 
